apiVersion: v1
kind: Service
metadata:
  name: cups
  namespace: cups
  labels:
    app.kubernetes.io/name: cups
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cups
  ports:
    - name: ipp
      port: 631
      targetPort: 631
      protocol: TCP
